more checks on ./publish

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -20,7 +20,6 @@ fi
 
 TEMPDIR=/tmp/irit-fr-maelvalais
 
-
 echo -e "${red}1)${end} ${yel}Cloning to ${green}$TEMPDIR${end}...${end}"
 echo -en "$gray"
 set -x
@@ -32,7 +31,6 @@ fi
 cd $TEMPDIR
 set +x
 echo -en "$gray"
-
 
 echo -e "${red}2)${end} ${yel}Updating ${green}maelvls.github.io${end}...${end}"
 echo -e "    ${green}note:${end} 'master' contains compiled code, 'source' is the actual hugo source"
@@ -53,6 +51,11 @@ git -C $MAELVLS_GITHUB_IO ci -m "update on $(date)" | cat || true
 git -C $MAELVLS_GITHUB_IO push origin master -f -q
 set +x
 echo -en "$end"
+
+if ! ssh bali.irit.fr -x 'date' >/dev/null; then
+    echo -e "${red}error:${end} ${yel}ssh bali.irit.fr${end} not working (see in ~/.ssh/config)${end}" >&2
+    exit 1
+fi
 
 echo -e "${red}3)${end} ${yel}Updating irit.fr/~Mael.Valais...${end}"
 
